Repository surveyjs/survey-library, pull requests merged in 2021-07, with the labels that each got.

#3114 Add SurveyElement isQuestion property #3113
  src/question.ts
  src/survey-element.ts
  tests/surveytests.ts
Labels: Implemented, enhancement

#3116 Fix: Null exception on showing preview in file question located in dy…
  src/question.ts
  tests/questionFileTests.ts
Labels: bug, fixed

#3118 Fix: The first title action fired on pressing enter in a text editor #3117
  src/knockout/components/action-bar/action-bar-item.html
  src/react/components/action-bar/action-bar-item.tsx
  src/vue/components/action-bar/action-bar-item.vue
Labels: bug, fixed

#3120 Add checks on survey in file to avoid errors calls from async functio…
  src/question_file.ts
Labels: bug, fixed

#3135 Refactor rendering survey logo&title #3134
  src/base.ts
  src/knockout/templates/header.html
  src/react/components/survey-header/survey-header.tsx
  src/survey.ts
  src/vue/header.vue
  tests/surveytests.ts
Labels: enhancement

#3139 Accessibility updates
  src/knockout/components/svg-icon/svg-icon.html
  src/knockout/templates/question-dropdown.html
  src/knockout/templates/question-errors.html
  src/react/components/svg-icon/svg-icon.tsx
  src/react/reactquestion.tsx
  src/react/reactquestion_dropdown.tsx
  src/vue/components/svg-icon/svg-icon.vue
  src/vue/dropdown.vue
  src/vue/errors.vue
Labels: enhancement

#3159 Removed running TestCafe tests on jQuery
  examples_test/bootstrap/jquery.html
  examples_test/default/jquery.html
  examples_test/modern/jquery.html
  testCafe/dxService/runSurveyOneTime.js
  testCafe/helper.js
  testCafe/survey/changeRendering.js
  testCafe/survey/customCss.js
Labels: Implemented, enhancement
