Repository surveyjs/survey-library, pull requests merged in 2022-12, with the labels that each got.

#5232 Note about unique question names
  docs/design-survey-create-a-simple-survey.md
  src/question_baseselect.ts
  src/survey-element.ts
Labels: update documentation

#5258 New Case: Questions share same values
  docs/Troubleshooting.md
  src/survey-element.ts
Labels: Docs

#5308 Accessibility Issue: The screenreader doesn't announce the Required option state
  packages/survey-angular-ui/src/components/action-bar/action-bar-item.component.html
  src/actions/action.ts
  src/knockout/components/action-bar/action-bar-item.html
  src/react/components/action-bar/action-bar-item.tsx
  src/vue/components/action-bar/action-bar-item.vue
  tests/markup/snapshots/file-mob2-zip-png-ro.snap.html
  tests/markup/snapshots/file-mob2-zip-png.snap.html
  tests/markup/snapshots/paneldynamic-list.snap.html
  tests/markup/snapshots/paneldynamic-progress-bottom.snap.html
  tests/markup/snapshots/paneldynamic-progress-top.snap.html
  tests/markup/snapshots/paneldynamic-remove-btn-action-bar.snap.html
  tests/markup/snapshots/paneldynamic-remove-btn-right.snap.html
Labels: accessibility

#5372 Mention the latest supported Vue version
  docs/get-started-vue.md
Labels: update documentation

#5428 Add the isAnswerCorrect doc description
  src/question.ts
Labels: Docs

#5433 Update SurveyModel doccomments, part 1
  src/base.ts
  src/question.ts
  src/question_custom.ts
  src/question_file.ts
  src/survey.ts
Labels: Docs
