Repository surveyjs/survey-library, pull requests merged in 2023-05, with the labels that each got.

#6118 Update Third-Party Angular Component Integration with info about tree shaking
  docs/customize-question-types-third-party-component-integration-angular.md
Labels: documentation

#6141 Add info about defaultValueExpression to Populate Form Fields
  docs/design-survey-pre-populate-form-fields.md
Labels: documentation

#6151 Update CSS-related API descriptions
  src/survey-element.ts
  src/survey.ts
Labels: documentation

#6179 ranking shortcut shadows
  src/dragdrop/choices.ts
  src/dragdrop/matrix-rows.ts
  src/dragdrop/ranking-choices.ts
Labels: bug

#6204 Add demo links and other minor fixes
  docs/design-survey-pre-populate-form-fields.md
  src/actions/action.ts
Labels: documentation

#6208 Dynamic Panel: Describe `templateVisibleIf`, `visiblePanels`, `visiblePanelCount`
  src/question_paneldynamic.ts
Labels: documentation

#6170 Dropdown Question - WCAG 4.1.2, aria-required-attr - Required ARIA attributes not present: aria-expanded, aria-controls
  packages/survey-angular-ui/src/components/dropdown/dropdown.component.html
  packages/survey-angular-ui/src/components/tagbox/tagbox-filter.component.html
  packages/survey-angular-ui/src/components/tagbox/tagbox.component.html
  packages/survey-angular-ui/src/question.component.html
  src/knockout/components/dropdown/dropdown.html
  src/knockout/components/tagbox/tagbox.html
  src/knockout/templates/question.html
  src/question.ts
  src/question_dropdown.ts
  src/question_rating.ts
  src/question_tagbox.ts
  src/react/dropdown-base.tsx
  src/react/reactquestion.tsx
  src/react/reactquestion_tagbox.tsx
  src/react/tagbox-filter.tsx
  src/vue/components/dropdown/dropdown.vue
  src/vue/components/tagbox/tagbox-filter.vue
  src/vue/components/tagbox/tagbox.vue
  src/vue/element.vue
  tests/markup/etalon_dropdown.ts
  tests/markup/snapshots/dropdown-aria-expanded.snap.html
Labels: bug, accessibility

#6195 Looks like we haven't solved the issue with Russian font.
  src/defaultV2-theme/fonts.scss
  visualRegressionTests/tests/defaultV2/etalons/checkbox-col-count-0.png
  visualRegressionTests/tests/defaultV2/etalons/complex-question.png
  visualRegressionTests/tests/defaultV2/etalons/dropdown-input-position.png
  visualRegressionTests/tests/defaultV2/etalons/dropdown-rtl-question.png
  visualRegressionTests/tests/defaultV2/etalons/dropdown-search-spaces-prefix.png
  visualRegressionTests/tests/defaultV2/etalons/dropdown-search-spaces-suffix.png
  visualRegressionTests/tests/defaultV2/etalons/dropdown-select-question.png
  visualRegressionTests/tests/defaultV2/etalons/dropdown-with-markdown-popup.png
  visualRegressionTests/tests/defaultV2/etalons/file-question-long-name.png
  visualRegressionTests/tests/defaultV2/etalons/long-rating-in-panel.png
  visualRegressionTests/tests/defaultV2/etalons/matrixdynamic-allowRowsDragAndDrop.png
  visualRegressionTests/tests/defaultV2/etalons/matrixdynamic-allowRowsDragAndDrop_mask.png
  visualRegressionTests/tests/defaultV2/etalons/matrixdynamic-errors-in-cell.png
  visualRegressionTests/tests/defaultV2/etalons/matrixdynamic-vertical.png
  visualRegressionTests/tests/defaultV2/etalons/matrixdynamic.png
  visualRegressionTests/tests/defaultV2/etalons/paneldynamic-tabs-with-title.png
  visualRegressionTests/tests/defaultV2/etalons/paneldynamic-tabs-without-title.png
  visualRegressionTests/tests/defaultV2/etalons/question-collapse-hover-focus.png
  visualRegressionTests/tests/defaultV2/etalons/question-collapse.png
  visualRegressionTests/tests/defaultV2/etalons/question-hidden-title-actions-long-title.png
  visualRegressionTests/tests/defaultV2/etalons/question-matrix-detail-hover.png
  visualRegressionTests/tests/defaultV2/etalons/question-matrix-detail.png
  visualRegressionTests/tests/defaultV2/etalons/question-matrix-dropdown-columns.png
  visualRegressionTests/tests/defaultV2/etalons/question-matrix-dropdown-top-align.png
  visualRegressionTests/tests/defaultV2/etalons/question-matrix-non-latin.png
  visualRegressionTests/tests/defaultV2/etalons/question-matrixdynamic-remaining-character-counter.png
  visualRegressionTests/tests/defaultV2/etalons/question-rating-dropdown.png
  visualRegressionTests/tests/defaultV2/etalons/question-required.png
  visualRegressionTests/tests/defaultV2/etalons/question-title-actions-long-title.png
  visualRegressionTests/tests/defaultV2/etalons/responsiveness-matrixdynamic.png
  visualRegressionTests/tests/defaultV2/etalons/save-data-error.png
  visualRegressionTests/tests/defaultV2/etalons/save-data-saving.png
  visualRegressionTests/tests/defaultV2/etalons/save-data-success.png
  visualRegressionTests/tests/defaultV2/etalons/survey-custom-navigation.png
  visualRegressionTests/tests/defaultV2/etalons/survey-progress-bar-top-buttons.png
  visualRegressionTests/tests/defaultV2/etalons/survey-progress-bar-top.png
  visualRegressionTests/tests/defaultV2/etalons/tagbox-contrast-input.png
  visualRegressionTests/tests/defaultV2/etalons/tagbox-focused.png
  visualRegressionTests/tests/defaultV2/etalons/tagbox-question-long-items-overlay-tablet-popup.png
  visualRegressionTests/tests/defaultV2/etalons/tagbox-question-multiline-selected-items.png
  visualRegressionTests/tests/defaultV2/etalons/tagbox-question-overlay-tablet-popup-big.png
  visualRegressionTests/tests/defaultV2/etalons/tagbox-question-overlay-tablet-popup.png
  visualRegressionTests/tests/defaultV2/etalons/tagbox-question.png
  visualRegressionTests/tests/defaultV2/etalons/tagbox-rtl-question.png
Labels: bug

#6210 A11y better structure
  package.json
  packages/survey-angular-ui/src/questions/comment.component.html
  packages/survey-angular-ui/src/questions/text.component.html
  src/entries/chunks/model.ts
  src/knockout/koquestion_multipletext.ts
  src/knockout/templates/question-comment.html
  src/knockout/templates/question-text.html
  src/question_multipletext.ts
  src/question_textbase.ts
  src/react/reactquestion_comment.tsx
  src/react/reactquestion_text.tsx
  src/vue/comment.vue
  src/vue/text-input.vue
  testCafe/a11y/textbase.ts
  testCafe/questions/allTypes.js
  testCafe/questions/progressButtons.js
  testCafe/questions/text.js
  testCafe/survey/composite_components.ts
  tests/a11y.ts
  tests/markup/snapshots/page-swnl-title-v2.snap.html
  tests/markup/snapshots/page-title-v2.snap.html
  tests/markup/snapshots/panel-page-swnl-title-v2.snap.html
  tests/markup/snapshots/panel-question-headers.snap.html
  tests/markup/snapshots/panel-text.snap.html
  tests/markup/snapshots/paneldynamic-no-footer-1.snap.html
  tests/markup/snapshots/paneldynamic-no-footer-2.snap.html
  tests/markup/snapshots/paneldynamic-remove-btn-action-bar.snap.html
  tests/markup/snapshots/paneldynamic-remove-btn-right.snap.html
  tests/markup/snapshots/question-errors-v2-bottom.snap.html
  tests/markup/snapshots/question-errors-v2-top.snap.html
  tests/markup/snapshots/question-title-with-html.snap.html
  tests/markup/snapshots/question-with-indent.snap.html
Labels: bug, accessibility, user issue, mobile/tablet

#6249 Update focus-related API descriptions
  src/panel.ts
  src/survey.ts
Labels: documentation
