Repository surveyjs/survey-library, pull requests merged in 2023-11, with the labels that each got.

#7299 Add info about passing a custom error message in `onUploadFiles`, `onDownloadFile`, `onClearFiles`
  src/survey-events-api.ts
Labels: documentation

#7304 Add build instructions for survey-angular-ui and survey-vue3-ui
  README.md
  build-scripts/survey-angular/README.md
  build-scripts/survey-core/README.md
  build-scripts/survey-jquery/README.md
  build-scripts/survey-knockout-ui/README.md
  build-scripts/survey-knockout/README.md
  build-scripts/survey-react-ui/README.md
  build-scripts/survey-react/README.md
  build-scripts/survey-vue-ui/README.md
  build-scripts/survey-vue/README.md
  packages/survey-angular-ui/README.md
  packages/survey-vue3-ui/README.md
Labels: documentation

#7269 PR: A11Y Dropdpwn + Icons
  packages/survey-angular-ui/src/components/dropdown/dropdown.component.html
  packages/survey-angular-ui/src/components/svg-icon/svg-icon.component.ts
  packages/survey-angular-ui/src/components/tagbox/tagbox.component.html
  packages/survey-vue3-ui/src/components/dropdown/Dropdown.vue
  packages/survey-vue3-ui/src/components/svg-icon/SvgIcon.vue
  packages/survey-vue3-ui/src/components/tagbox/Tagbox.vue
  src/knockout/components/dropdown/dropdown.html
  src/knockout/components/svg-icon/svg-icon.html
  src/knockout/components/tagbox/tagbox.html
  src/react/components/svg-icon/svg-icon.tsx
  src/react/dropdown-base.tsx
  src/vue/components/dropdown/dropdown.vue
  src/vue/components/svg-icon/svg-icon.vue
  src/vue/components/tagbox/tagbox.vue
  testCafe/questions/dropdown.js
  tests/markup/snapshots/dropdown-aria-expanded.snap.html
  tests/markup/snapshots/dropdown-input-string.snap.html
  tests/markup/snapshots/dropdown-select-clear-button.snap.html
  tests/markup/snapshots/dropdown-with-markdown.snap.html
  tests/markup/snapshots/dropdown-with-none-value.snap.html
  tests/markup/snapshots/dropdown-with-other-value.snap.html
  tests/markup/snapshots/file-2-png.snap.html
  tests/markup/snapshots/file-2-zip-png-file-navigator.snap.html
  tests/markup/snapshots/file-2-zip-png-ro.snap.html
  tests/markup/snapshots/file-2-zip-png.snap.html
  tests/markup/snapshots/file-2-zip.snap.html
  tests/markup/snapshots/file-2.snap.html
  tests/markup/snapshots/file-mob2-png.snap.html
  tests/markup/snapshots/file-mob2-zip-png-ro.snap.html
  tests/markup/snapshots/file-mob2-zip-png.snap.html
  tests/markup/snapshots/file-mob2-zip.snap.html
  tests/markup/snapshots/file-mob2.snap.html
  tests/markup/snapshots/file-mode-both.snap.html
  tests/markup/snapshots/file-mode-camera.snap.html
  tests/markup/snapshots/file-modern-png.snap.html
  tests/markup/snapshots/file-modern-zip-png.snap.html
  tests/markup/snapshots/file-modern-zip.snap.html
  tests/markup/snapshots/file-playing-video.snap.html
  tests/markup/snapshots/matrixdynamic-default.snap.html
  tests/markup/snapshots/matrixdynamic-defaultV2.snap.html
  tests/markup/snapshots/matrixdynamic-totals.snap.html
  tests/markup/snapshots/paneldynamic-no-footer-1.snap.html
  tests/markup/snapshots/paneldynamic-no-footer-2.snap.html
  tests/markup/snapshots/paneldynamic-progress-tab-center.snap.html
  tests/markup/snapshots/paneldynamic-progress-tab-left.snap.html
  tests/markup/snapshots/paneldynamic-progress-tab-right.snap.html
  tests/markup/snapshots/rating-as-dropdown-readonly-with-value.snap.html
  tests/markup/snapshots/rating-as-dropdown-readonly.snap.html
  tests/markup/snapshots/rating-as-dropdown.snap.html
  tests/markup/snapshots/rating-smileys.snap.html
  tests/markup/snapshots/rating-stars.snap.html
  tests/markup/snapshots/tagbox-mobile.snap.html
  tests/markup/snapshots/tagbox-selected.snap.html
  tests/markup/snapshots/tagbox-without-search.snap.html
  tests/markup/snapshots/tagbox.snap.html
Labels: bug, accessibility, user issue

#7318 PR: A11Y: Single-Selection Matrix
  packages/survey-angular-ui/src/questions/matrix.component.html
  packages/survey-vue3-ui/src/Matrix.vue
  src/knockout/templates/question-matrix.html
  src/martixBase.ts
  src/react/reactquestion_matrix.tsx
  src/vue/matrix.vue
  tests/markup/snapshots/matrix-mobile-v2.snap.html
  tests/markup/snapshots/matrix-modern.snap.html
  tests/markup/snapshots/matrix-v2.snap.html
  tests/markup/snapshots/matrix-widths.snap.html
  tests/question_matrix_base_tests.ts
Labels: bug, accessibility, user issue

#7349 Describe `settings.specialChoicesOrder`
  src/question.ts
  src/question_baseselect.ts
  src/settings.ts
Labels: documentation

#7339 PR: A11Y Matrix-Dropdown (Multi-Select)
  packages/survey-angular-ui/src/questions/matrix.component.html
  packages/survey-vue3-ui/src/Matrix.vue
  src/knockout/templates/question-matrix.html
  src/martixBase.ts
  src/question_matrixdropdownbase.ts
  src/question_matrixdropdowncolumn.ts
  src/question_matrixdropdownrendered.ts
  src/react/reactquestion_matrix.tsx
  src/vue/matrix.vue
  testCafe/questions/allTypes.js
  tests/markup/snapshots/martix-celltype-text-a11y.snap.html
  tests/markup/snapshots/matrixdropdown-cell-errors-bottom.snap.html
  tests/markup/snapshots/matrixdropdown-cell-errors-top.snap.html
  tests/markup/snapshots/matrixdropdown-vertical.snap.html
  tests/markup/snapshots/matrixdropdown.snap.html
  tests/markup/snapshots/matrixdynamic-show-in-multiple-columns-mobile.snap.html
  tests/question_matrixdropdownbasetests.ts
  tests/question_matrixdynamictests.ts
  tests/surveytests.ts
Labels: bug, accessibility, user issue

#7365 Update `signatureAutoScaleEnabled` description
  src/question_signaturepad.ts
Labels: documentation

#7370 PR: LIBRARY: Change onDragDropAllow options
  src/drag-drop-page-helper-v1.ts
  src/survey-events-api.ts
Labels: API change

#7335 Describe the `notify` method
  src/survey.ts
Labels: documentation

#7428 Link Demo for defaultValueExpression
  src/question.ts
Labels: documentation
