Repository surveyjs/survey-library, pull requests merged in 2023-10, with the labels that each got.

#7082 Describe `setValueIf` and `setValueExpression`
  src/question.ts
Labels: documentation

#7091 PR: A11Y: DropDown: Placeholder sounds more than needed
  packages/survey-angular-ui/src/components/dropdown/dropdown.component.html
  packages/survey-angular-ui/src/components/tagbox/tagbox-filter.component.html
  packages/survey-vue3-ui/src/components/dropdown/Dropdown.vue
  packages/survey-vue3-ui/src/components/tagbox/TagboxFilter.vue
  src/knockout/components/dropdown/dropdown.html
  src/knockout/components/tagbox/tagbox.html
  src/react/dropdown-base.tsx
  src/react/tagbox-filter.tsx
  src/vue/components/dropdown/dropdown.vue
  src/vue/components/tagbox/tagbox-filter.vue
  tests/markup/snapshots/dropdown-aria-expanded.snap.html
  tests/markup/snapshots/dropdown-input-string.snap.html
  tests/markup/snapshots/dropdown-select-clear-button.snap.html
  tests/markup/snapshots/dropdown-select-mobile.snap.html
  tests/markup/snapshots/dropdown-select.snap.html
  tests/markup/snapshots/dropdown-with-markdown.snap.html
  tests/markup/snapshots/dropdown-with-none-value.snap.html
  tests/markup/snapshots/dropdown-with-other-value.snap.html
  tests/markup/snapshots/matrixdynamic-default.snap.html
  tests/markup/snapshots/matrixdynamic-defaultV2.snap.html
  tests/markup/snapshots/rating-as-dropdown-with-value-focused.snap.html
  tests/markup/snapshots/rating-as-dropdown.snap.html
  tests/markup/snapshots/tagbox-mobile.snap.html
  tests/markup/snapshots/tagbox-selected.snap.html
  tests/markup/snapshots/tagbox-without-clear-button.snap.html
  tests/markup/snapshots/tagbox-without-search.snap.html
  tests/markup/snapshots/tagbox.snap.html
Labels: bug, accessibility, user issue

#7103 PR: New dialog's shadow issue.
  src/common-styles/sv-popup.scss
Labels: bug

#7102 Describe theme API and fix theme applying instructions
  docs/manage-default-themes-and-styles.md
  docs/sidebar.json
  src/survey.ts
  src/themes.ts
Labels: documentation

#7107 PR: Ranking long item text
  src/common-styles/sv-ranking.scss
  src/dragdrop/ranking-choices.ts
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-select-to-rank.png
Labels: bug

#7113 Docs: Update the Localization topic
  docs/survey-localization.md
Labels: documentation

#7111 Docs: Describe PageModel.navigationDescription
  src/page.ts
Labels: documentation

#7115 PR: Ranking: Counting Issue
  src/dragdrop/ranking-select-to-rank.ts
  tests/dragdrophelpertests.ts
Labels: bug

#7132 Testcafe: Blinking: reqOpts of undefined
  package.json
  testCafe/questions/dropdown.js
Labels: bug

#7139 PR: Ranking: UX Enchancements: Shortcut Issue
  src/dragdrop/core.ts
Labels: bug

#7157 Describe the `IHeader` interface and related properties
  docs/sidebar.json
  src/cover.ts
  src/survey.ts
  src/themes.ts
  tests/coverTests.ts
Labels: documentation

#7158 Describe `settings.autoAdvanceDelay`
  src/settings.ts
  src/survey.ts
Labels: documentation

#7150 PR: Ranking: Remove some code duplication in ranking question code: Issues
  src/question_ranking.ts
  tests/question_ranking_tests.ts
Labels: enhancement

#7149 PR: Ranking: UX Enchancements: Root
  src/common-styles/sv-ranking.scss
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-select-to-rank-vertical.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-select-to-rank.png
Labels: bug

#7186 PR: Ranking. Let's change the height of question's panel.
  src/dragdrop/ranking-select-to-rank.ts
Labels: enhancement

#7201 Update the `setValueExpression` description
  src/question.ts
Labels: documentation

#7239 PR: Ranking: Devices: Elemets Rendered Incorrectly
  src/dragdrop/dom-adapter.ts
  tests/dragdrophelpertests.ts
Labels: bug

#7249 PR: Check clean JSON structure
  src/question_comment.ts
  tests/jsonobjecttests.ts
  tests/surveytests.ts
Labels: bug

#7246 PR: Ranking: Cleaner JSON
  src/question_ranking.ts
  tests/question_ranking_tests.ts
Labels: bug
