Repository surveyjs/survey-library, pull requests merged in 2023-12, with the labels that each got.

#7459 PR: Dropdown's Clear Button - A11Y
  packages/survey-angular-ui/src/components/dropdown/dropdown.component.html
  packages/survey-angular-ui/src/components/tagbox/tagbox.component.html
  packages/survey-vue3-ui/src/components/dropdown/Dropdown.vue
  packages/survey-vue3-ui/src/components/tagbox/Tagbox.vue
  src/knockout/components/dropdown/dropdown.html
  src/knockout/components/tagbox/tagbox.html
  src/react/dropdown-base.tsx
  src/vue/components/dropdown/dropdown.vue
  src/vue/components/tagbox/tagbox.vue
  testCafe/questions/dropdown.js
  tests/markup/snapshots/dropdown-aria-expanded.snap.html
  tests/markup/snapshots/dropdown-input-focused.snap.html
  tests/markup/snapshots/dropdown-input-string.snap.html
  tests/markup/snapshots/dropdown-select-clear-button.snap.html
  tests/markup/snapshots/dropdown-with-markdown.snap.html
  tests/markup/snapshots/dropdown-with-none-value.snap.html
  tests/markup/snapshots/dropdown-with-other-value.snap.html
  tests/markup/snapshots/matrixdynamic-default.snap.html
  tests/markup/snapshots/matrixdynamic-defaultV2.snap.html
  tests/markup/snapshots/matrixdynamic-totals.snap.html
  tests/markup/snapshots/tagbox-mobile.snap.html
  tests/markup/snapshots/tagbox-selected.snap.html
  tests/markup/snapshots/tagbox-without-search.snap.html
  tests/markup/snapshots/tagbox.snap.html
Labels: bug, accessibility

#7463 PR: [Ranking] Option to override default placeholder text
  packages/survey-angular-ui/src/questions/ranking.component.html
  packages/survey-vue3-ui/src/Ranking.vue
  src/knockout/templates/question-ranking.html
  src/question_ranking.ts
  src/react/reactquestion_ranking.tsx
  src/vue/ranking/ranking.vue
  tests/markup/snapshots/ranking-selectToRankEnabled-empty.snap.html
  tests/markup/snapshots/ranking-selectToRankEnabled-vertical.snap.html
  tests/question_ranking_tests.ts
Labels: enhancement, documentation, user issue

#7493 Multiple Textboxes: Rename `titleWidth` to `itemTitleWidth` and update its description
  packages/survey-angular-ui/src/questions/mutlipletextitem.component.html
  packages/survey-vue3-ui/src/MultipletextItem.vue
  src/knockout/templates/question-multipletext.html
  src/question_multipletext.ts
  src/react/reactquestion_multipletext.tsx
  src/vue/multipletextitem.vue
  visualRegressionTests/tests/defaultV2/multipletext.ts
Labels: documentation

#7531 PR: Popup Survey for jQuery - The allowClose option doesn't enable the Close button
  src/entries/angular.ts
  src/entries/jquery.ts
  src/knockout/templates/window.html
Labels: bug

#7533 survey.mergeData API - Update a link to the doc topic
  src/survey.ts
Labels: bug, documentation

#7537 Remove obsolete global settings from the docs
  src/settings.ts
Labels: documentation

#7539 Add Third-Party Vue 3 Component Integration tutorial (fix #7408)
  docs/customize-question-types-create-composite-question-types.md
  docs/customize-question-types-create-specialized-question-types.md
  docs/customize-question-types-third-party-component-integration-angular.md
  docs/customize-question-types-third-party-component-integration-react.md
  docs/customize-question-types-third-party-component-integration-vue.md
  docs/sidebar.json
Labels: documentation

#7532 PR: LIBRARY: Animation: Focus and Selected State
  src/defaultV2-theme/blocks/sd-checkbox.scss
  src/defaultV2-theme/blocks/sd-input.scss
  src/defaultV2-theme/blocks/sd-item.scss
  src/defaultV2-theme/blocks/sd-radio.scss
  src/defaultV2-theme/variables.scss
  src/themes/borderless-dark-panelless.ts
  src/themes/borderless-dark.ts
  src/themes/borderless-light-panelless.ts
  src/themes/borderless-light.ts
  src/themes/contrast-dark-panelless.ts
  src/themes/contrast-dark.ts
  src/themes/contrast-light-panelless.ts
  src/themes/contrast-light.ts
  src/themes/default-dark-panelless.ts
  src/themes/default-dark.ts
  src/themes/default-light-panelless.ts
  src/themes/default-light.ts
  src/themes/doubleborder-dark-panelless.ts
  src/themes/doubleborder-dark.ts
  src/themes/doubleborder-light-panelless.ts
  src/themes/doubleborder-light.ts
  src/themes/flat-dark-panelless.ts
  src/themes/flat-dark.ts
  src/themes/flat-light-panelless.ts
  src/themes/flat-light.ts
  src/themes/layered-dark-panelless.ts
  src/themes/layered-dark.ts
  src/themes/layered-light-panelless.ts
  src/themes/layered-light.ts
  src/themes/plain-dark-panelless.ts
  src/themes/plain-dark.ts
  src/themes/plain-light-panelless.ts
  src/themes/plain-light.ts
  src/themes/predefined-themes.json
  src/themes/sharp-dark-panelless.ts
  src/themes/sharp-dark.ts
  src/themes/sharp-light-panelless.ts
  src/themes/sharp-light.ts
  src/themes/solid-dark-panelless.ts
  src/themes/solid-dark.ts
  src/themes/solid-light-panelless.ts
  src/themes/solid-light.ts
  src/themes/threedimensional-dark-panelless.ts
  src/themes/threedimensional-dark.ts
  src/themes/threedimensional-light-panelless.ts
  src/themes/threedimensional-light.ts
  themes-import.js
Labels: animation

#7582 temporary disalbed animation (https://github.com/surveyjs/survey-libr…
  src/defaultV2-theme/blocks/sd-checkbox.scss
  src/defaultV2-theme/blocks/sd-input.scss
  src/defaultV2-theme/blocks/sd-item.scss
  src/defaultV2-theme/blocks/sd-radio.scss
Labels: bug, animation

#7589 PR: IsTouch shouldn't be dependent on IsMobile
  src/utils/devices.ts
  tests/utilstests.ts
Labels: bug
