Repository surveyjs/survey-library, pull requests merged in 2023-07, with the labels that each got.

#6457 PR: Ranking - Select to rank: Change area placeholders
  packages/survey-angular-ui/src/questions/ranking.component.html
  src/knockout/templates/question-ranking.html
  src/localization/english.ts
  src/question_ranking.ts
  src/react/reactquestion_ranking.tsx
  src/vue/ranking/ranking.vue
  tests/markup/snapshots/ranking-selectToRankEnabled-empty.snap.html
  tests/markup/snapshots/ranking-selectToRankEnabled-vertical.snap.html
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-select-to-rank-vertical.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-select-to-rank.png
Labels: bug, enhancement

#6487 PR: Ranking: Select To Rank: UX Issues
  src/common-styles/sv-ranking.scss
  src/dragdrop/core.ts
  src/dragdrop/ranking-select-to-rank.ts
  src/question_ranking.ts
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-select-to-rank-vertical.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-select-to-rank.png
Labels: bug, enhancement

#6518 File: Describe `allowCameraAccess`
  src/question_file.ts
Labels: documentation

#6461 Theming drag drop ghost element
  src/base-interfaces.ts
  src/dragdrop/choices.ts
  src/dragdrop/core.ts
  src/dragdrop/dom-adapter.ts
  src/dragdrop/matrix-rows.ts
  src/dragdrop/ranking-choices.ts
  src/survey.ts
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-shortcut-position-container-layout.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-shortcut-position-container-layout_mask.png
  visualRegressionTests/tests/defaultV2/ranking.ts
Labels: enhancement

#6574 Describe `options.isAfterPreview` in onCurrentPageChanging/Changed
  src/survey-events-api.ts
Labels: documentation

#6575 Describe `PopupSurveyModel.allowClose`
  src/popup-survey.ts
Labels: documentation

#6530 Update `SurveyModel` doccomments
  src/survey-events-api.ts
  src/survey.ts
Labels: documentation

#6612 PR: support minSelectedChoices for ranking(selectToRank) and checkboxes
  src/question_checkbox.ts
  src/question_ranking.ts
  src/question_text.ts
  tests/surveyquestiontests.ts
Labels: enhancement
