Repository surveyjs/survey-library, pull requests merged in 2023-08, with the labels that each got.

#6648 PR: Ranking question with only one choice does not show choice
  src/question_ranking.ts
  testCafe/questions/ranking.js
  tests/question_ranking_tests.ts
Labels: bug

#6659 LIBRARY: PR: Ranking Question - The selectToRankEnabled setting is not available in a Property Grid
  src/question_ranking.ts
Labels: bug

#6704 Add a README for the Vue 3 package
  build-scripts/survey-vue-ui/README.md
  packages/survey-vue3-ui/README.md
Labels: documentation

#6697 Add documentation for the new theming mechanism
  docs/get-started-angular.md
  docs/get-started-jquery.md
  docs/get-started-knockout.md
  docs/get-started-react.md
  docs/get-started-vue.md
  docs/images/survey-library-themes.png
  docs/images/theme-editor.png
  docs/images/theme-export.png
  docs/manage-default-themes-and-styles.md
Labels: documentation

#6716 Add Get Started for Vue 3
  docs/get-started-vue.md
Labels: documentation

#6708 Update `SurveyModel` doccomments
  src/settings.ts
  src/survey-events-api.ts
  src/survey.ts
Labels: documentation

#6723 Describe `choiceValuesFromQuestion` and `choiceTextsFromQuestion`
  src/question_baseselect.ts
Labels: documentation

#6731 `onComplete`/`onCompleting`: Describe the `completeTrigger` parameter
  src/survey-events-api.ts
  src/survey.ts
Labels: documentation

#6756 Describe value types for different question types
  src/question.ts
Labels: documentation

#6762 Describe `settings.confirmActionAsync`
  src/settings.ts
Labels: documentation

#6778 PR: Survey Creator landing: Drag and drop doesn't work
  src/dragdrop/core.ts
  testCafe/questions/ranking.js
Labels: bug

#6772 PR: Ranking: New Issues
  src/common-styles/sv-ranking.scss
  src/defaultV2-theme/blocks/sd-ranking.scss
  src/dragdrop/choices.ts
  tests/dragdrophelpertests.ts
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-select-to-rank.png
Labels: bug

#6802 PR: Checkbox / Radio Group. Item removing doesn't work (iPad)
  src/dragdrop/dom-adapter.ts
Labels: bug, mobile/tablet

#6801 `SurveyModel`: Update API descriptions
  src/survey-events-api.ts
  src/survey.ts
Labels: documentation
