Repository surveyjs/survey-library, pull requests merged in 2023-06, with the labels that each got.

#6288 The 'Ensures every form element has a label' accessibility issue occurs for a Matrix Dropdown with Text cells
  src/question_textbase.ts
  tests/markup/etalon_matrix.ts
  tests/markup/snapshots/martix-celltype-text-a11y.snap.html
Labels: bug, accessibility

#6188 Start use native TestCafe service/API in all our f-tests
  .testcaferc.json
  package.json
  src/dropdownListModel.ts
  src/main-default-theme.scss
  src/modern/blocks/sv-body.scss
  src/popup-view-model.ts
  src/popup.ts
  testCafe/components/popup.ts
  testCafe/questions/boolean.js
  testCafe/questions/matrixdynamic_totals.js
  testCafe/questions/paneldynamic.ts
  testCafe/survey/workWithData.js
  visualRegressionTests/helper.ts
  visualRegressionTests/tests/defaultV2/etalons/popup-dropdown-short-list.png
  visualRegressionTests/tests/defaultV2/etalons/popup-modal-short-list-with-title.png
  visualRegressionTests/tests/defaultV2/etalons/popup-modal-short-list.png
  visualRegressionTests/tests/defaultV2/etalons/popup-overlay-long-list.png
  visualRegressionTests/tests/defaultV2/etalons/popup-overlay-short-list.png
  visualRegressionTests/tests/defaultV2/etalons/tagbox-question-overlay-tablet-popup-small.png
  visualRegressionTests/tests/defaultV2/panel.ts
  visualRegressionTests/tests/defaultV2/popup.ts
  visualRegressionTests/tests/defaultV2/survey.ts
  visualRegressionTests/tests/defaultV2/tagbox.ts
Labels: enhancement

#6356 Dynamic Matrix - Row texts are selected when a row is being dragged
  src/dragdrop/matrix-rows.ts
Labels: bug

#6368 Signature Pad issue on Android Pixel devices - A previously defined signature is reset
  package.json
  src/question_signaturepad.ts
Labels: bug, user issue

#6384 SurveyModel: Update matrix-related API descriptions
  src/question.ts
  src/survey-events-api.ts
  src/survey.ts
Labels: documentation

#6344 Ranking - selectToRank PR
  packages/survey-angular-ui/src/questions/ranking-item.component.html
  packages/survey-angular-ui/src/questions/ranking-item.component.ts
  packages/survey-angular-ui/src/questions/ranking.component.html
  packages/survey-angular-ui/src/questions/ranking.component.ts
  src/common-styles/sv-ranking.scss
  src/defaultCss/cssmodern.ts
  src/defaultCss/cssstandard.ts
  src/defaultCss/defaultV2Css.ts
  src/defaultV2-theme/variables.scss
  src/dragdrop/ranking-choices.ts
  src/dragdrop/ranking-select-to-rank.ts
  src/entries/chunks/model.ts
  src/knockout/templates/question-ranking.html
  src/localization/english.ts
  src/plugins/themes/bootstrap/cssbootstrap.ts
  src/plugins/themes/bootstrapmaterial/cssbootstrapmaterial.ts
  src/question_ranking.ts
  src/react/reactquestion_ranking.tsx
  src/vue/ranking/ranking-item.vue
  src/vue/ranking/ranking.vue
  testCafe/questions/ranking.js
  tests/dragdrophelpertests.ts
  tests/markup/etalon_ranking.ts
  tests/markup/snapshots/ranking-selectToRankEnabled-empty.snap.html
  tests/markup/snapshots/ranking-selectToRankEnabled-vertical.snap.html
  tests/question_ranking_tests.ts
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-select-to-rank-vertical.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-select-to-rank.png
  visualRegressionTests/tests/defaultV2/ranking.ts
Labels: enhancement, user issue

#6410 Signature Pad: problems after lib update
  src/question_signaturepad.ts
  testCafe/questions/signature.ts
Labels: bug

#6415 SurveyModel: Update doccomments for timer-related and onAfterRender* APIs
  src/page.ts
  src/question_file.ts
  src/survey-events-api.ts
  src/survey.ts
Labels: documentation

#6453 Update triggers, actions, and Service-related API descriptions
  src/survey-events-api.ts
  src/survey.ts
Labels: documentation
