Repository surveyjs/survey-library, pull requests merged in 2023-03, with the labels that each got.

#5721 Update `settings` doccomments
  docs/sidebar.json
  src/question_matrixdropdownbase.ts
  src/settings.ts
Labels: Docs

#5735 Ranking: display flex
  src/common-styles/sv-ranking.scss
Labels: bug

#5755 Correct CSS links from jquery to knockout
  docs/get-started-knockout.md
Labels: update documentation

#5828 useDisplayValuesInDynamicTexts is not used in Expressions
  src/question.ts
Labels: documentation

#5844 Update Angular version and note
  packages/survey-angular-ui/README.md
Labels: documentation

#5857 Add a link to the Form Input Validation demo
  src/validator.ts
Labels: documentation

#5892 Describe addLayoutElement and update the navigationTitle description
  src/page.ts
  src/survey.ts
Labels: documentation

#5905 Drag-n-Drop Issue
  src/dragdrop/survey-elements.ts
  tests/dragdrop_v2_tests.ts
Labels: bug

#5900 Ranking Issues
  src/common-styles/sv-ranking.scss
  src/defaultV2-theme/blocks/sd-ranking.scss
  src/dragdrop/choices.ts
  src/dragdrop/matrix-rows.ts
  src/dragdrop/ranking-choices.ts
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-hover-item.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-readonly.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-size.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking.png
  visualRegressionTests/tests/defaultV2/etalons/responsiveness-ranking-hover-item.png
  visualRegressionTests/tests/defaultV2/etalons/responsiveness-ranking.png
Labels: bug

#5906 Describe `SurveyModel`, part 2
  src/survey-events-api.ts
  src/survey.ts
Labels: documentation
