Repository surveyjs/survey-library, pull requests merged in 2023-09, with the labels that each got.

#6847 PR: Ranking Question - Drag & Drop works on disabled ("Editable if" -> "False") choices
  src/common-styles/sv-ranking.scss
  src/question_ranking.ts
  tests/question_ranking_tests.ts
Labels: bug, user issue

#6850 `SurveyModel`: Update doccomments for `get...` methods
  src/survey.ts
Labels: documentation

#6851 PR: React only: Ranking on Mobile Screens - The drag icon is suddenly lost if you drag an item by holding the drag icon
  src/dragdrop/dom-adapter.ts
  src/question_ranking.ts
Labels: bug, mobile/tablet

#6824 PR: File Question. Button breaks after removing the file (Safari)
  src/defaultV2-theme/blocks/sd-file.scss
Labels: bug

#6906 Update the Create Custom Widgets help topic
  docs/customize-question-types-create-custom-widgets.md
  docs/sidebar.json
Labels: documentation

#6924 Update `SurveyModel` API descriptions
  src/question_textbase.ts
  src/survey-events-api.ts
  src/survey.ts
Labels: documentation

#6943 Update PopupSurveyModel API descriptions
  src/popup-survey.ts
Labels: documentation

#6961 Expressions: Describe the `displayValue()` and `propertyValue()` functions
  docs/design-survey-conditional-logic.md
Labels: documentation

#6973 PR: Text selection during the drag-n-drop (Safari, again)
  src/dragdrop/dom-adapter.ts
Labels: bug

#7027 PR: HTML Question - new A11Y structure
  src/question_html.ts
  tests/markup/snapshots/page-swnl-v2.snap.html
  tests/markup/snapshots/panel-page-swnl-v2.snap.html
  tests/markup/snapshots/panel-swnl-v2.snap.html
  tests/markup/snapshots/panel.snap.html
  tests/markup/snapshots/survey-navigation.snap.html
Labels: bug, accessibility, user issue

#7015 PR: Implement a proprietary confirmation dialog
  src/common-styles/sv-popup.scss
  src/default-styles.scss
  src/defaultV2-theme/blocks/sd-button.scss
  src/localization/english.ts
  src/plugins/themes/common-theme-settings.ts
  src/popup-utils.ts
  src/popup.ts
  src/settings.ts
  src/utils/utils.ts
  src/vue/components/popup/popup-container.vue
  testCafe/questions/file.js
  visualRegressionTests/tests/defaultV2/etalons/paneldynamic-confirm-dialog.png
  visualRegressionTests/tests/defaultV2/paneldynamic.ts
Labels: enhancement
