Repository surveyjs/survey-library, pull requests merged in 2024-11, with the labels that each got.

#9047 PR: Library: V2: Icons: Issues: move out from core
  build-scripts/survey-angular/tsconfig.typing.angular.json
  build-scripts/survey-core/tsconfig.icons.json
  build-scripts/survey-core/webpack.icons.config.js
  build-scripts/survey-jquery-ui/tsconfig.typing.jquery-ui.json
  build-scripts/survey-jquery/tsconfig.typing.jquery.json
  build-scripts/survey-js-ui/tsconfig.json
  build-scripts/survey-knockout-ui/tsconfig.typing.ko-ui.json
  build-scripts/survey-knockout/tsconfig.typing.ko.json
  build-scripts/survey-react-ui/tsconfig.json
  build-scripts/survey-react/tsconfig.typing.react.json
  build-scripts/survey-vue-ui/tsconfig.typing.vue-ui.json
  build-scripts/survey-vue/tsconfig.typing.vue.json
  build-scripts/tsconfig.json
  build-scripts/tsconfig.tests.json
  build-scripts/webpack.common.js
  package.json
  packages/survey-angular-ui/src/survey.component.ts
  packages/survey-angular-ui/src/svgbundle.component.ts
  packages/survey-core/src/iconsV1.ts
  packages/survey-core/src/iconsV2.ts
  packages/survey-core/src/settings.ts
  packages/survey-core/src/survey.ts
  packages/survey-core/src/svgbundle.ts
  packages/survey-core/webpack.config.js
  packages/survey-react-ui/src/reactSurvey.tsx
  packages/survey-react-ui/src/svgbundle.tsx
  packages/survey-vue3-ui/src/Survey.vue
  packages/survey-vue3-ui/src/SvgBundle.vue
  src/knockout/kosurvey.ts
  src/vue/survey.vue
  tsconfig.json
Labels: v2.0

#9090 Update the `settings.serialization` API description
  packages/survey-core/src/settings.ts
Labels: documentation

#9105 PR: aria-describedby id generation checks for title instead of description
  packages/survey-core/src/question.ts
  packages/survey-core/tests/a11y.ts
  tests/markup/snapshots/boolean-disabled.snap.html
  tests/markup/snapshots/boolean-readonly.snap.html
  tests/markup/snapshots/boolean-v2.snap.html
  tests/markup/snapshots/boolean-value-v2.snap.html
  tests/markup/snapshots/boolean.snap.html
  tests/markup/snapshots/layout-page-swnl-title-v2.snap.html
  tests/markup/snapshots/layout-panel-page-swnl-title-v2.snap.html
  tests/markup/snapshots/page-questionTitleWidth.snap.html
  tests/markup/snapshots/page-swnl-title-v2.snap.html
  tests/markup/snapshots/page-title-v2.snap.html
  tests/markup/snapshots/panel-page-swnl-title-v2.snap.html
  tests/markup/snapshots/question-errors-v2-bottom.snap.html
  tests/markup/snapshots/question-errors-v2-top.snap.html
  tests/markup/snapshots/question-with-indent.snap.html
Labels: accessibility, user issue
