Repository surveyjs/survey-library, pull requests merged in 2024-03, with the labels that each got.

#7941 PR: Ranking: Issue
  src/dragdrop/ranking-select-to-rank.ts
  tests/dragdrophelpertests.ts
Labels: bug

#7953 PR: A question drag item's tooltip appears far from the mouse pointer
  src/dragdrop/core.ts
  tests/dragdrophelpertests.ts
Labels: bug, user issue

#7976 Describe the Masks API
  docs/sidebar.json
  src/mask/mask_base.ts
  src/mask/mask_currency.ts
  src/mask/mask_datetime.ts
  src/mask/mask_numeric.ts
  src/mask/mask_pattern.ts
  src/question_text.ts
  src/settings.ts
  src/survey.ts
Labels: documentation

#7980 Describe the `onMatrixDetailPanelVisibleChanged` event
  src/survey-events-api.ts
  src/survey.ts
Labels: documentation

#7982 Describe the `textWrapEnabled` property
  src/question_dropdown.ts
Labels: documentation

#7979 PR Drag-Drop doesn't work with Shadow-Dom
  src/dragdrop/core.ts
  src/dragdrop/dom-adapter.ts
  tests/dragdrophelpertests.ts
Labels: bug, user issue

#8003 PR(2): Drag-and-drop doesn't work with shadow DOM
  src/dragdrop/core.ts
  src/dragdrop/dom-adapter.ts
  tests/dragdrophelpertests.ts
Labels: bug, user issue

#8025 Describe `MultipleTextItemModel`
  docs/sidebar.json
  src/question_matrixdropdowncolumn.ts
  src/question_multipletext.ts
  src/question_text.ts
Labels: documentation
