Repository surveyjs/survey-library, pull requests merged in 2024-02, with the labels that each got.

#7806 PR: KO: Survey doesn't have title and description if loaded via SurveyID
  src/knockout/kosurvey.ts
  src/knockout/templates/header.html
Labels: bug

#7724 PR: Popup Survey - Introduce a "full screen" mode
  packages/survey-angular-ui/example/src/app/components/test/test.component.html
  packages/survey-angular-ui/src/popup.survey.component.html
  packages/survey-angular-ui/src/popup.survey.component.ts
  packages/survey-vue3-ui/example/src/components/test/TestCommon.vue
  packages/survey-vue3-ui/src/PopupSurvey.vue
  src/common-styles/window.scss
  src/defaultCss/cssmodern.ts
  src/defaultCss/cssstandard.ts
  src/defaultCss/defaultV2Css.ts
  src/defaultV2-theme/blocks/mixins.scss
  src/entries/angular.ts
  src/entries/jquery.ts
  src/images/back-to-panel_16x16.svg
  src/images/full-screen_16x16.svg
  src/knockout/koPopupSurvey.ts
  src/knockout/templates/window.html
  src/popup-survey.ts
  src/react/react-popup-survey.tsx
  src/vue/popup-survey.vue
  testCafe/helper.js
  tests/surveyWindowTests.ts
  visualRegressionTests/tests/defaultV2/etalons/survey-popup--collapsed.png
  visualRegressionTests/tests/defaultV2/etalons/survey-popup--full-screen.png
  visualRegressionTests/tests/defaultV2/etalons/survey-popup.png
  visualRegressionTests/tests/defaultV2/survey-popup.ts
Labels: enhancement, user issue

#7819 Fixed https://github.com/surveyjs/private-tasks/issues/366 - KO: Survey doesn't have title and description if loaded via SurveyID
  src/survey.ts
  tests/surveytests.ts
Labels: bug

#7835 Describe `transposeData`
  src/question_matrixdropdownbase.ts
  src/question_matrixdynamic.ts
Labels: documentation

#7825 PR: Pop-Up Survey - Fix the popup width
  src/common-styles/window.scss
Labels: enhancement

#7839 Update `confirmActionFunc` and `confirmActionAsync` descriptions
  src/settings.ts
Labels: documentation

#7841 Describe the `parentPanel` prefix
  docs/design-survey-conditional-logic.md
Labels: documentation

#7832 PR: Ranking. Scrolbar appears in the Select to Rank mode.
  src/common-styles/sv-ranking.scss
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-select-to-rank.png
Labels: bug

#7854 PR: Pop-Up Survey - The minimize and close button do not work on a small screen
  src/common-styles/window.scss
Labels: bug

#7866 fix drag-drop shortcut position with fitToContainer true (scroll issue)
  src/dragdrop/dom-adapter.ts
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-shortcut-position-container-layout.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-shortcut-position-container-relative-layout.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-shortcut-position-container-scroll-layout.png
  visualRegressionTests/tests/defaultV2/ranking.ts
Labels: bug

#7879 PR: Themes Tab - The 'Yes, reset the theme' button appears beyond the popup window's boundaries
  src/common-styles/sv-popup.scss
  src/utils/utils.ts
  visualRegressionTests/tests/defaultV2/etalons/paneldynamic-confirm-dialog--long-button-text.png
  visualRegressionTests/tests/defaultV2/paneldynamic.ts
Labels: bug, user issue, theme builder

#7894 PR: Ranking: SelectToRank: Hor Layout: Can't drop to empty "from-container"
  src/dragdrop/ranking-select-to-rank.ts
Labels: bug

#7896 PR: Ranking: selectToRank: number bug
  src/dragdrop/ranking-select-to-rank.ts
  tests/dragdrophelpertests.ts
Labels: bug

#7903 PR: Theme Message Box Issue (safari only)
  src/utils/utils.ts
  tests/utilstests.ts
Labels: bug
