Repository surveyjs/survey-library, pull requests merged in 2024-04, with the labels that each got.

#8061 Populate Form Fields: Describe question value format
  docs/design-survey-pre-populate-form-fields.md
Labels: documentation

#8060 Describe Variables vs Calculated values + How to add user ID to survey results (fix #8020)
  docs/customize-question-types-third-party-component-integration-vue.md
  docs/design-survey-conditional-logic.md
  docs/get-started-angular.md
  docs/get-started-jquery.md
  docs/get-started-knockout.md
  docs/get-started-react.md
  docs/get-started-vue.md
Labels: documentation

#8077 Image Picker: Describe min/maxImageWidth/Height
  src/question_imagepicker.ts
Labels: documentation

#8172 PR: SelectToRank with MaxSelectedChoices: can't able to unrank via drag
  src/question_ranking.ts
  tests/question_ranking_tests.ts
Labels: bug

#8204 work for the https://github.com/surveyjs/private-tasks/issues/363
  src/defaultV2-theme/blocks/sd-rating.scss
Labels: animation
