Repository surveyjs/survey-library, pull requests merged in 2024-10, with the labels that each got.

#8877 PR: Ranking order is lost when survey is reloaded
  packages/survey-core/src/question_ranking.ts
  packages/survey-core/tests/question_ranking_tests.ts
Labels: bug, user issue

#8934 Update the note in the `checkErrorsMode` description
  packages/survey-core/src/survey.ts
Labels: documentation

#8967 PR: Add ability to add css class into drag-n-drop ghost element
  packages/survey-core/src/common-styles/sv-drag-drop.scss
  packages/survey-core/src/defaultCss/defaultV2Css.ts
  packages/survey-core/src/dragdrop/matrix-rows.ts
  src/defaultCss/cssmodern.ts
  src/defaultCss/cssstandard.ts
  src/plugins/themes/bootstrap-integration/cssbootstrap.ts
  src/plugins/themes/bootstrap-material-integration/cssbootstrapmaterial.ts
Labels: enhancement, v2.0

#8974 Describe the `onGetPageNumber` event
  packages/survey-core/src/survey-events-api.ts
  packages/survey-core/src/survey.ts
  packages/survey-core/tests/surveytests.ts
Labels: documentation
