Repository surveyjs/survey-library, pull requests merged in 2024-09, with the labels that each got.

#8770 Feature/animations creator ko args
  src/knockout/components/action-bar/action-bar-item.ts
Labels: animation

#8806 Update Validators API descriptions
  packages/survey-core/src/validator.ts
Labels: documentation

#8689 PR: LIBRARY: Ranking Items Wrap Issues
  packages/survey-core/src/common-styles/sv-drag-drop.scss
  packages/survey-core/src/common-styles/sv-ranking.scss
  packages/survey-core/src/dragdrop/choices.ts
  packages/survey-core/src/dragdrop/ranking-choices.ts
  packages/survey-core/tests/dragdrophelpertests.ts
  src/default-styles.scss
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-hover-long-item.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-long-items.png
Labels: bug, enhancement

#8828 PR: Composite question elements are unreachable via VoiceOver cursor
  packages/survey-core/src/question_custom.ts
  packages/survey-core/tests/question_customtests.ts
Labels: accessibility, user issue

#8841 PR: Ranking new view — swap left and right sides.
  packages/survey-core/src/common-styles/sv-ranking.scss
  packages/survey-core/src/defaultCss/defaultV2Css.ts
  packages/survey-core/src/question_ranking.ts
  src/defaultCss/cssmodern.ts
  src/defaultCss/cssstandard.ts
  src/plugins/themes/bootstrap-material-integration/cssbootstrapmaterial.ts
  tests/markup/etalon_ranking.ts
  tests/markup/snapshots/ranking-selectToRankEnabled-SwapAreas.snap.html
Labels: enhancement

#8844 Update links to the Markdown demo
  packages/survey-core/src/question_baseselect.ts
  packages/survey-core/src/question_matrixdropdownbase.ts
  packages/survey-core/src/question_multipletext.ts
  packages/survey-core/src/question_rating.ts
Labels: documentation

#8857 PR: Multi-Select Matrix - A disabled checkbox is focusable
  packages/survey-core/src/question.ts
  packages/survey-core/tests/question_matrixdropdownbasetests.ts
Labels: bug, accessibility, user issue
