Repository surveyjs/survey-library, pull requests merged in 2024-07, with the labels that each got.

#8487 PR: Remove inline styles for list-item dnd shotrcut in creator because we can't add new color var for them
  src/dragdrop/choices.ts
  src/main.scss
Labels: bug

#8497 PR: [Angular] Users can change a dropdown value by clicking a read-only Dropdown field
  src/dropdownListModel.ts
  tests/dropdown_list_model_test.ts
Labels: bug, user issue

#8505 Describe the `commentAreaRows` property
  src/survey.ts
Labels: documentation

#8563 PR: Ranking carry-forward. Order is reset.
  src/question_ranking.ts
  tests/question_ranking_tests.ts
Labels: bug

#8570 Describe the `storeUtcDates` setting
  src/settings.ts
Labels: documentation

#8614 Cannot reorder items on Ranking on a mobile
  src/utils/devices.ts
Labels: bug, user issue, mobile/tablet
