Repository surveyjs/survey-library, pull requests merged in 2024-01, with the labels that each got.

#7632 Fix code snippet type in setting
  src/settings.ts
Labels: bug, documentation

#7649 Add `MatrixDropdownColumn` to the docs
  docs/sidebar.json
  docs/uri.json
  src/martixBase.ts
  src/panel.ts
  src/question.ts
  src/question_baseselect.ts
  src/question_matrixdropdownbase.ts
  src/question_matrixdropdowncolumn.ts
  src/survey-events-api.ts
Labels: documentation

#7576 PR: PopupSurveyModel: Redesign
  packages/survey-angular-ui/example/src/app/components/test/test.component.html
  packages/survey-angular-ui/example/src/app/components/test/test.component.ts
  packages/survey-angular-ui/src/popup.survey.component.html
  packages/survey-angular-ui/src/popup.survey.component.ts
  packages/survey-vue3-ui/example/src/components/test/TestCommon.vue
  packages/survey-vue3-ui/src/PopupSurvey.vue
  src/common-styles/window.scss
  src/defaultCss/cssmodern.ts
  src/defaultCss/cssstandard.ts
  src/defaultCss/defaultV2Css.ts
  src/images/close_16x16.svg
  src/images/minimize_16x16.svg
  src/images/restore_16x16.svg
  src/knockout/templates/window.html
  src/popup-survey.ts
  src/react/react-popup-survey.tsx
  src/vue/popup-survey.vue
  testCafe/helper.js
  testCafe/survey/popup.js
  tests/surveyWindowTests.ts
  visualRegressionTests/helper.ts
  visualRegressionTests/tests/defaultV2/etalons/survey-popup--collapsed.png
  visualRegressionTests/tests/defaultV2/etalons/survey-popup.png
  visualRegressionTests/tests/defaultV2/survey-popup.ts
Labels: enhancement, user issue

#7592 PR: Ranking: Carry Forward: Support Unarranged behavior
  src/dragdrop/ranking-select-to-rank.ts
  src/question_ranking.ts
  tests/question_ranking_tests.ts
Labels: enhancement, user issue

#7741 Describe how to verify survey results on a server
  docs/how-to-store-survey-results.md
Labels: documentation
