Repository surveyjs/survey-library, pull requests merged in 2024-06, with the labels that each got.

#8306 PR: Ranking - Support the `itemComponent` setting and allow developers to create a custom item template
  packages/survey-angular-ui/example/src/app/app.module.ts
  packages/survey-angular-ui/example/src/app/components/itemContentTemplateComponent.html
  packages/survey-angular-ui/example/src/app/components/itemContentTemplateComponent.ts
  packages/survey-angular-ui/src/angular-ui.module.ts
  packages/survey-angular-ui/src/angular-ui.ts
  packages/survey-angular-ui/src/questions/ranking-item-content.component.html
  packages/survey-angular-ui/src/questions/ranking-item-content.component.ts
  packages/survey-angular-ui/src/questions/ranking-item.component.html
  packages/survey-vue3-ui/example/src/components/test/test-custom-components/ItemContent.vue
  packages/survey-vue3-ui/example/src/main.ts
  packages/survey-vue3-ui/src/RankingItem.vue
  packages/survey-vue3-ui/src/RankingItemContent.vue
  packages/survey-vue3-ui/src/index.ts
  src/entries/react-ui-model.ts
  src/entries/vue-ui-model.ts
  src/knockout/components/ranking/item-content.html
  src/knockout/components/ranking/item-content.ts
  src/knockout/koquestion_ranking.ts
  src/knockout/templates/question-ranking.html
  src/question_ranking.ts
  src/react/reactquestion_ranking.tsx
  src/vue/ranking/ranking-item-content.vue
  src/vue/ranking/ranking-item.vue
  testCafe/helper.js
  tests/jsonobjecttests.ts
  tests/surveyquestiontests.ts
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-custom-item-content.png
  visualRegressionTests/tests/defaultV2/ranking.ts
Labels: enhancement, user issue

#8355 PR: LIbrary: Reordering / Dragging of ranking questions in logic builder has poor placement
  src/common-styles/sv-popup.scss
Labels: bug, user issue

#8395 PR: Read-Only Dropdown with an empty string placeholder has a wrong input size
  src/defaultV2-theme/blocks/sd-dropdown.scss
  visualRegressionTests/tests/defaultV2/dropdown.ts
  visualRegressionTests/tests/defaultV2/etalons/dropdown-readonly-empty-placeholder.png
Labels: bug, user issue

#8422 PR: Preview - dropdown value changes on click on preview screen
  src/dropdownListModel.ts
  tests/dropdown_list_model_test.ts
Labels: bug, user issue

#8441 PR: Dropdown appears as a popup on an HP touch screen
  src/global_variables_utils.ts
  src/utils/devices.ts
  tests/utilstests.ts
Labels: usability, user issue

#8455 Add a note about date input fields to the `checkErrorsMode` description
  src/survey.ts
Labels: documentation

#8423 PR: Ranking: Use the itemContentComponent behavior and functionality for itemComponent
  packages/survey-angular-ui/example/src/app/components/itemContentTemplateComponent.ts
  packages/survey-angular-ui/src/questions/ranking-item-content.component.ts
  packages/survey-angular-ui/src/questions/ranking-item.component.html
  packages/survey-angular-ui/src/questions/ranking.component.ts
  packages/survey-vue3-ui/src/Ranking.vue
  packages/survey-vue3-ui/src/RankingItem.vue
  packages/survey-vue3-ui/src/index.ts
  src/knockout/components/ranking/item-content.ts
  src/knockout/templates/question-ranking.html
  src/question_ranking.ts
  src/react/reactquestion_ranking.tsx
  src/vue/ranking/ranking-item-content.vue
  src/vue/ranking/ranking-item.vue
  tests/jsonobjecttests.ts
  tests/surveyquestiontests.ts
  visualRegressionTests/tests/defaultV2/ranking.ts
Labels: bug

#8463 Describe the `settings.dropdownSearchDelay` property
  src/settings.ts
Labels: documentation

#8467 PR: Questions with checkboxes - Roles provided for the checkboxes are not valid
  packages/survey-angular-ui/src/questions/checkbox-item.component.html
  packages/survey-vue3-ui/src/CheckboxItem.vue
  src/knockout/templates/question-checkbox.html
  src/question.ts
  src/question_checkbox.ts
  src/question_expression.ts
  src/react/reactquestion_checkbox.tsx
  src/vue/checkboxitem.vue
  tests/markup/helper.ts
  tests/markup/snapshots/checkbox-columns-head-foot.snap.html
  tests/markup/snapshots/checkbox-columns-mobile.snap.html
  tests/markup/snapshots/checkbox-columns-no-head-foot.snap.html
  tests/markup/snapshots/checkbox-columns.snap.html
  tests/markup/snapshots/checkbox-comment-V2.snap.html
  tests/markup/snapshots/checkbox-disabled.snap.html
  tests/markup/snapshots/checkbox-modern.snap.html
  tests/markup/snapshots/checkbox-other-V2.snap.html
  tests/markup/snapshots/checkbox-other-maxlength.snap.html
  tests/markup/snapshots/checkbox-other.snap.html
  tests/markup/snapshots/checkbox-readonly-selected.snap.html
  tests/markup/snapshots/checkbox-readonly.snap.html
  tests/markup/snapshots/checkbox-row-head-foot.snap.html
  tests/markup/snapshots/checkbox-row-no-head-foot.snap.html
  tests/markup/snapshots/checkbox-v2.snap.html
  tests/markup/snapshots/checkbox.snap.html
  tests/markup/snapshots/matrixdynamic-show-in-multiple-columns-mobile.snap.html
  tests/markup/snapshots/matrixdynamic-show-in-multiple-columns.snap.html
Labels: bug, accessibility, user issue
