Repository surveyjs/survey-library, pull requests merged in 2024-08, with the labels that each got.

#8651 PR: LIBRARY: Safari: Unexpected page's focus.
  src/dragdrop/core.ts
  tests/dragdrophelpertests.ts
Labels: bug

#8657 Describe `onOpenDropdownMenu`
  src/survey-events-api.ts
  src/survey.ts
Labels: documentation

#8511 PR: [Ranking] Auto-line wrap in too long choice options
  src/common-styles/sv-ranking.scss
  src/default-styles.scss
  src/dragdrop/dom-adapter.ts
  src/dragdrop/ranking-choices.ts
  src/question_ranking.ts
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-custom-item-content.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-hover-long-item.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-item-theme.png
  visualRegressionTests/tests/defaultV2/etalons/question-ranking-long-items.png
  visualRegressionTests/tests/defaultV2/etalons/survey-theme-desktop-input-size.png
  visualRegressionTests/tests/defaultV2/etalons/survey-theme-questiontitle-font-color-for-items.png
  visualRegressionTests/tests/defaultV2/ranking.ts
Labels: enhancement, user issue

#8661 PR: Can unselect the disable item in the ranking question
  src/question_ranking.ts
  tests/question_ranking_tests.ts
Labels: bug

#8681 Describe `validateVisitedEmptyFIelds`
  packages/survey-core/src/survey.ts
Labels: documentation

#8646 PR: Brand Info. New design.
  packages/survey-angular-ui/src/survey-content.component.html
  packages/survey-core/src/common-styles/sv-brand-info.scss
  packages/survey-react-ui/src/reactSurvey.tsx
  packages/survey-vue3-ui/src/Survey.vue
  src/knockout/templates/index.html
  src/vue/survey.vue
  visualRegressionTests/tests/defaultV2/brandinfo.ts
  visualRegressionTests/tests/defaultV2/etalons/brand-info-image.png
  visualRegressionTests/tests/defaultV2/etalons/survey-progress-bar-bottom-brand.png
Labels: bug, enhancement

#8706 Update survey-js-ui README
  README.md
  build-scripts/survey-core/README.md
  build-scripts/survey-js-ui/README.md
  packages/survey-core/README.md
Labels: documentation

#8724 PR: CodeSandbox Issue - Could not find dependency: 'jquery' relative to '/node_modules/survey-js-ui/survey-js-ui.js
  src/entries/js-ui.ts
Labels: bug

#8730 Describe `inputTextAlignment`
  packages/survey-core/src/question_multipletext.ts
  packages/survey-core/src/question_text.ts
Labels: documentation

#8746 PR: LIBRARY: Creator: Hover Animations
  packages/survey-angular-ui/src/components/action-bar/action-bar-item.component.html
  packages/survey-core/src/actions/action.ts
  packages/survey-react-ui/src/components/action-bar/action-bar-item.tsx
  packages/survey-vue3-ui/src/components/action-bar/ActionBarItem.vue
  src/vue/components/action-bar/action-bar-item.vue
Labels: v2.0, animation
