Repository surveyjs/survey-library, pull requests merged in 2024-12, with the labels that each got.

#9075 PR: Library: Library Only: Dynamic matrix's row drag-n-drop
  packages/survey-core/src/common-styles/sv-drag-drop.scss
  packages/survey-core/src/defaultV2-theme/blocks/sd-matrixdynamic.scss
  packages/survey-core/src/question_matrixdropdownrendered.ts
  packages/survey-core/src/question_matrixdynamic.ts
  visualRegressionTests/tests/defaultV2/etalons/matrixdynamic-allowRowsDragAndDrop-lockedRowCount-2.png
  visualRegressionTests/tests/defaultV2/etalons/matrixdynamic-allowRowsDragAndDrop-lockedRowCount.png
  visualRegressionTests/tests/defaultV2/etalons/matrixdynamic-allowRowsDragAndDrop.png
  visualRegressionTests/tests/defaultV2/matrixdynamic.ts
Labels: enhancement

#9159 PR:Boolean Question in RTL mode - Yes/No labels disappear
  packages/survey-core/src/defaultV2-theme/blocks/sd-boolean.scss
  visualRegressionTests/tests/defaultV2/boolean.ts
  visualRegressionTests/tests/defaultV2/etalons/boolean-question-rtl.png
Labels: bug, user issue

#9180 Update the `parent`, `isPanel`, and `isPage` descriptions
  packages/survey-core/src/panel.ts
  packages/survey-core/src/survey-element.ts
Labels: documentation

#9196 Implement the `dateAdd` function
  packages/survey-core/src/functionsfactory.ts
  packages/survey-core/tests/expressions/expressionParserTest.ts
Labels: enhancement

#9218 SurveyModel: Rename `completeLastPage()` to `tryComplete()`
  docs/design-survey-create-a-multi-page-survey.md
  packages/survey-core/src/survey.ts
  packages/survey-core/tests/paneltests.ts
  packages/survey-core/tests/question_baseselecttests.ts
  packages/survey-core/tests/question_customtests.ts
  packages/survey-core/tests/question_matrix_tests.ts
  packages/survey-core/tests/question_matrixdynamictests.ts
  packages/survey-core/tests/question_multipletexttests.ts
  packages/survey-core/tests/question_paneldynamic_tests.ts
  packages/survey-core/tests/question_texttests.ts
  packages/survey-core/tests/surveyShowPreviewTests.ts
  packages/survey-core/tests/surveyquestiontests.ts
  packages/survey-core/tests/surveytests.ts
  packages/survey-core/tests/surveytriggertests.ts
  testCafe/survey/customNavigation.js
  tests/markup/etalon_matrixdropdown.ts
  tests/markup/etalon_multipletext.ts
Labels: v2.0

#9217 #9210 SurveyModel: renamings - onScrollingElementToTop, onIsAnswerCorrect
  packages/survey-core/src/question.ts
  packages/survey-core/src/survey-events-api.ts
  packages/survey-core/src/survey.ts
  packages/survey-core/tests/surveytests.ts
Labels: v2.0
