Repository surveyjs/survey-library, pull requests merged in 2025-06, with the labels that each got.

#9968 PR: Uncaught TypeError: Cannot read properties of null (reading 'renderedHtml')
  packages/survey-angular-ui/src/questions/matrixcell.component.html
  packages/survey-angular-ui/src/questions/matrixdropdowncell.component.ts
  packages/survey-core/src/martixBase.ts
  packages/survey-core/src/question_matrixdropdownbase.ts
  packages/survey-core/src/question_matrixdropdowncolumn.ts
  packages/survey-core/tests/question_matrix_base_tests.ts
  packages/survey-react-ui/src/reactquestion_matrix.tsx
  packages/survey-react-ui/src/reactquestion_matrixdropdownbase.tsx
  packages/survey-vue3-ui/src/MatrixCell.vue
  packages/survey-vue3-ui/src/MatrixDropdownCellComp.vue
Labels: bug

#10005 Docs: Describe `QuestionSliderModel`
  packages/survey-core/src/question_slider.ts
Labels: documentation

#9952 PR-2: LIBRARY: Slider (Range) Question
  packages/survey-angular-ui/src/angular-ui.module.ts
  packages/survey-angular-ui/src/angular-ui.ts
  packages/survey-angular-ui/src/components/slider/slider-label-item.component.html
  packages/survey-angular-ui/src/components/slider/slider-label-item.component.ts
  packages/survey-angular-ui/src/questions/slider.component.html
  packages/survey-angular-ui/src/questions/slider.component.ts
  packages/survey-core/src/itemvalue.ts
  packages/survey-core/src/question_slider.ts
  packages/survey-core/tests/question_slider_tests.ts
  packages/survey-react-ui/entries/react-ui-model.ts
  packages/survey-react-ui/src/components/slider/slider-label-item.tsx
  packages/survey-react-ui/src/reactquestion_slider.tsx
  packages/survey-vue3-ui/src/Slider.vue
  packages/survey-vue3-ui/src/components/slider/SliderLabelItem.vue
  packages/survey-vue3-ui/src/components/slider/slider.ts
  packages/survey-vue3-ui/src/index.ts
Labels: enhancement

#10036 PR: Slider bugs
  packages/survey-angular-ui/src/questions/slider.component.html
  packages/survey-core/src/question_slider.ts
  packages/survey-core/tests/question_slider_tests.ts
  packages/survey-react-ui/src/reactquestion_slider.tsx
  packages/survey-vue3-ui/src/Slider.vue
  tests/markup/snapshots/slider-default-value-range-mode.snap.html
  tests/markup/snapshots/slider-range-mode.snap.html
  tests/markup/snapshots/slider-read-only-range-mode.snap.html
Labels: bug
