Repository surveyjs/survey-library, pull requests merged in 2025-01, with the labels that each got.

#9222 `SurveyModel`: Misc renamings - sendResultOnPageNext, maxOthersLength, lazyRendering
  functionalTests/dxService/runSurveyOneTime.js
  packages/survey-core/docs/surveyjs_definition.json
  packages/survey-core/src/base-interfaces.ts
  packages/survey-core/src/question.ts
  packages/survey-core/src/survey.ts
  packages/survey-core/tests/jsonSchemaTests.ts
  packages/survey-core/tests/paneltests.ts
  packages/survey-core/tests/surveytests.ts
  tests/markup/etalon_checkbox.ts
Labels: v2.0

#9232 Rename settings.showItemsInOrder fix #6407
  functionalTests/dxService/loadSurvey.js
  functionalTests/helper.js
  functionalTests/questions/checkboxes.js
  functionalTests/survey/focusFirstQuestionAutomatic.ts
  packages/survey-core/src/question_baseselect.ts
  packages/survey-core/src/settings.ts
  packages/survey-core/tests/question_baseselecttests.ts
  tests/markup/etalon_checkbox.ts
  tests/markup/etalon_radiogroup.ts
  visualRegressionTests/helper.ts
  visualRegressionTests/tests/defaultV2/imagepicker.ts
  visualRegressionTests/tests/defaultV2/question.ts
  visualRegressionTests/tests/defaultV2/selectbase.ts
Labels: breaking change

#9216 Reset default imageHeight and imageWidth for Images
  packages/survey-core/src/question_imagepicker.ts
  packages/survey-core/tests/questionImagepicker.ts
  visualRegressionTests/tests/defaultV2/etalons/imagepicker-responsive-col-count-1.png
  visualRegressionTests/tests/defaultV2/etalons/imagepicker-responsive-col-count-3.png
  visualRegressionTests/tests/defaultV2/etalons/imagepicker-responsive-max.png
Labels: v2.0

#9244 SurveyModel: Split the `showPreviewBeforeComplete` property in two
  packages/survey-core/src/survey.ts
  packages/survey-core/tests/surveyShowPreviewTests.ts
Labels: breaking change, API change, v2.0

#9215 Reset default logoHeight and logoWidth for survey
  packages/survey-core/src/survey.ts
  packages/survey-core/tests/surveytests.ts
  visualRegressionTests/tests/defaultV2/etalons/survey-advanced-header-default.png
  visualRegressionTests/tests/defaultV2/etalons/survey-advanced-header-mobile-background.png
  visualRegressionTests/tests/defaultV2/etalons/survey-advanced-header-mobile-default.png
  visualRegressionTests/tests/defaultV2/etalons/survey-advanced-header-mobile-with-overlap.png
  visualRegressionTests/tests/defaultV2/etalons/survey-advanced-header-width-by-survey.png
  visualRegressionTests/tests/defaultV2/etalons/survey-advanced-header-with-overlap.png
  visualRegressionTests/tests/defaultV2/etalons/survey-logo-right-without-title.png
  visualRegressionTests/tests/defaultV2/etalons/survey-title-with-logo.png
  visualRegressionTests/tests/defaultV2/etalons/survey-toc-advanced-header-mobile-with-overlap.png
  visualRegressionTests/tests/defaultV2/etalons/survey-toc-advanced-header-with-overlap.png
Labels: breaking change, v2.0

#9309 Boolean questions: Remove the `label` and `showTitle` properties
  packages/survey-core/src/question_boolean.ts
Labels: API change, v2.0

#9355 PR: [survey-angular-ui] The Cannot read properties of undefined (reading 'id') exception is thrown when implementing the survey.onAfterRenderQuestionInput functiuon
  packages/survey-core/src/survey.ts
Labels: bug

#9370 Update build instructions in READMEs
  README.md
  packages/survey-angular-ui/README.md
  packages/survey-core/README.md
  packages/survey-js-ui/README.md
  packages/survey-react-ui/README.md
  packages/survey-vue3-ui/README.md
Labels: documentation

#9375 Add descriptions for the Grid Layout API
  packages/survey-core/src/panel.ts
  packages/survey-core/src/survey-element.ts
  packages/survey-core/src/survey.ts
Labels: documentation
