Repository surveyjs/survey-library, pull requests merged in 2025-04, with the labels that each got.

#9695 `PanelModel`: Describe the parameter in the `expand()` method
  packages/survey-core/src/panel.ts
Labels: documentation

#9718 Hide expand/collapse properties for `PageModel`
  packages/survey-core/src/panel.ts
  packages/survey-core/src/survey-element.ts
Labels: documentation

#9726 Dropdown: Describe custom choices API
  packages/survey-core/src/question_dropdown.ts
  packages/survey-core/src/question_tagbox.ts
  packages/survey-core/src/survey-events-api.ts
  packages/survey-core/src/survey.ts
Labels: documentation

#9706 Describe `storeDefaults` in `toJSON()`
  packages/survey-core/src/base.ts
Labels: documentation

#9738 PR: Single-Select Matrix - A screen reader announces too much information when selecting each option
  packages/survey-angular-ui/src/questions/matrix.component.html
  packages/survey-react-ui/src/reactquestion_matrix.tsx
  packages/survey-vue3-ui/src/Matrix.vue
  tests/markup/snapshots/matrix-empty.snap.html
  tests/markup/snapshots/matrix-mobile-v2.snap.html
  tests/markup/snapshots/matrix-modern.snap.html
  tests/markup/snapshots/matrix-v2-disabled.snap.html
  tests/markup/snapshots/matrix-v2-readonly.snap.html
  tests/markup/snapshots/matrix-v2.snap.html
  tests/markup/snapshots/matrix-widths.snap.html
Labels: accessibility, user issue

#9748 PR: Boolean Question - When selecting a value for the first time, the Yes label is not announced by a narrator
  packages/survey-react-ui/src/boolean.tsx
Labels: bug, accessibility, user issue

#9763 File Upload: Update `imageHeight` and `imageWIdth` descriptions
  packages/survey-core/src/question_file.ts
Labels: documentation
