Repository surveyjs/survey-library, pull requests merged in 2025-07, with the labels that each got.

#10106 PR: Library VRT: Ranking: Blinks
  e2e/helper.ts
  screenshots/ranking.spec.ts
  screenshots/ranking.spec.ts-snapshots/question-ranking-shortcut-position-container-layout.png
  screenshots/ranking.spec.ts-snapshots/question-ranking-shortcut-position-container-relative-layout.png
  screenshots/ranking.spec.ts-snapshots/question-ranking-shortcut-position-container-scroll-layout.png
Labels: bug

#10121 PR: Rating Scale - A screen reader doesn't announce a question title when the question receives the focus
  packages/survey-angular-ui/src/components/rating/rating-item-smiley.component.html
  packages/survey-angular-ui/src/components/rating/rating-item-star.component.html
  packages/survey-angular-ui/src/components/rating/rating-item.component.html
  packages/survey-angular-ui/src/questions/rating.component.html
  packages/survey-core/src/question_rating.ts
  packages/survey-react-ui/src/components/rating/rating-item-smiley.tsx
  packages/survey-react-ui/src/components/rating/rating-item-star.tsx
  packages/survey-react-ui/src/components/rating/rating-item.tsx
  packages/survey-react-ui/src/reactquestion_rating.tsx
  packages/survey-vue3-ui/src/Rating.vue
  packages/survey-vue3-ui/src/components/rating/RatingItem.vue
  packages/survey-vue3-ui/src/components/rating/RatingItemSmiley.vue
  packages/survey-vue3-ui/src/components/rating/RatingItemStar.vue
  tests/markup/snapshots/rating-as-wrappable.snap.html
  tests/markup/snapshots/rating-display-mode.snap.html
  tests/markup/snapshots/rating-min-max-items.snap.html
  tests/markup/snapshots/rating-min-max.snap.html
  tests/markup/snapshots/rating-simple-disabled.snap.html
  tests/markup/snapshots/rating-simple-readonly.snap.html
  tests/markup/snapshots/rating-simple.snap.html
  tests/markup/snapshots/rating-smileys-disabled.snap.html
  tests/markup/snapshots/rating-smileys-readonly.snap.html
  tests/markup/snapshots/rating-smileys.snap.html
  tests/markup/snapshots/rating-stars-disabled.snap.html
  tests/markup/snapshots/rating-stars-readonly.snap.html
  tests/markup/snapshots/rating-stars.snap.html
Labels: bug, accessibility, user issue

#10147 Add a code example to the `confirmActionAsync` description
  packages/survey-core/src/settings.ts
Labels: documentation

#10162 Update the `confirmActionFunc` and `confirmActionAsync` descriptions
  packages/survey-core/src/settings.ts
Labels: documentation

#10170 PR: https://github.com/surveyjs/survey-library/issues/10154
  accessibilityTests/questions.spec.ts
  packages/survey-angular-ui/src/errors.component.ts
  packages/survey-core/src/question.ts
  packages/survey-react-ui/src/reactquestion.tsx
  packages/survey-vue3-ui/src/Errors.vue
  tests/markup/snapshots/matrixdropdown-cell-errors-bottom.snap.html
  tests/markup/snapshots/matrixdropdown-cell-errors-top.snap.html
  tests/markup/snapshots/multipletext-error-bottom-v2.snap.html
  tests/markup/snapshots/multipletext-error-top-v2.snap.html
  tests/markup/snapshots/question-errors-v2-bottom.snap.html
  tests/markup/snapshots/question-errors-v2-top.snap.html
Labels: accessibility

#10184 Single-Select Matrix: Describe the `cellType` property
  packages/survey-core/src/question_matrix.ts
Labels: documentation
